This is makeindex, version 2.15 [MiKTeX 2.9.6840 64-bit] (kpathsea + Thai support).
Scanning style file ./report.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file report.acn....done (3 entries accepted, 0 rejected).
Sorting entries....done (4 comparisons).
Generating output file report.acr....done (9 lines written, 0 warnings).
Output written in report.acr.
Transcript written in report.alg.
